from .base_value_function import BaseValueFunction
from .q_value_function import QValueFunction
from .ttt_heuristic_value_function import TTTHeuristicValueFunction
from .ttt_heuristic_value_function_fast import TTTHeuristicValueFunctionFast
from .ttt_heuristic_value_function_gt import TTTHeuristicValueFunctionGT
